# Generated by Django 4.1.3 on 2022-11-02 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50, unique=True)),
                ('project_tags', multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('JS', 'JavaScript'), ('PG', 'Postgres'), ('SQL', 'SQLite'), ('OOP', 'Object Oriented Programming'), ('AUTH', 'Authentication')], max_length=50)),
                ('project_description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
