# Generated by Django 4.1.3 on 2022-12-15 18:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='animate_image',
            field=models.ImageField(default='puppy.gif', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('PY', 'Python'), ('DJA', 'Django'), ('JS', 'JavaScript'), ('PG', 'Postgres'), ('SQL', 'SQLite'), ('OOP', 'Object Oriented Programming'), ('AUTH', 'Authentication'), ('ECRP', 'Encryption'), ('TCSS', 'Tailwind CSS')], max_length=50),
        ),
    ]
